name: Build and Test Trampoline
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  setup:
    name: Build Package (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
