name: Build and Test Trampoline
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  setup:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Restore Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Build Package
        run: npm run build
